# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SSD Slide Decks for Trainers
description: >
  A collection of slide decks for surveillance self-defense trainings.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
collections:
  decks:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "decks" # a collection in your site, in plural form
    values:
      layout: "deck"
